Completed issue-4-delete-entry - Barbara Liao
barbara-liao/code-journal pull request #8
Opened 2021-09-11 15:45 UTC by barbara-liao

![issue-4-delete-entry screenshot](https://user-images.githubusercontent.com/87685216/132953511-38ef635d-ea71-4f0b-8fc8-ef5356686381.gif)

2021-09-11 15:47 UTC, barbara-liao commented
no focaccia this time!!

2021-09-14 16:18 UTC, codingcodymiller requested changes

2021-09-14 16:18 UTC, codingcodymiller commented on js/main.js
> +$confirm.addEventListener('click', handleConfirmData);
You should just make this into one event listener since both pieces of work are related to the same job.

2021-09-14 16:18 UTC, codingcodymiller commented on js/main.js
> +}
Based on my above comment, these two functions will be merged

2021-09-16 16:36 UTC, codingcodymiller approved these changes

2021-09-16 18:26 UTC, merged